### ISSUE TITLE
lc-validation-summary scripts are blocked by plunkr - Now plunkr doesn't allow loading scripts over http but https

### ISSUE THREAD

**Issue by Totemika** [Lemoncode/lc-validation-summary#50]
http://lemoncode.github.io/lc-validation-summary/#customValidations

SEE SNAPSHOT: 
![image](https://cloud.githubusercontent.com/assets/4906291/11559802/e72015c4-99bb-11e5-85ac-7ad41922965d.png)

**Comment by brauliodiez** [comment]
is just matter to change the href or do we need to rewrite the samples?

**Comment by Totemika** [comment]
no rewriting, just providing the scripts from an https source instead just http.

plunkr is blocking all <scripts src="http://..."/> references when the **src** is http and not https and the plunkr is embedded instead of being edited

**Comment by Totemika** [comment]
This issue seems to be solved.

**Comment by brauliodiez** [comment]
Thanks for the update
